'use strict'
import mm from 'micromatch'

const patterns = [
  // wild
  '**/*.log',
  '**/.d00',
  '**/.DS_Store',
  '**/.tdck',
  '**/.thumbnails/',
  '**/.gs/',
  '**/.cache/',
  '**/tmp/',
  '**/tmp/',
  '**/temp/',
  '**/.gs_fs*',
  '**/.mn_*',
  '**/.td-*',
  '**/.thumbcache_*',
  '**/.thumbcache_idx_*',
  '**/.tmfs/',
  '**/.xdkj.de.new.*',
  '**/.yz/',
  '**/.um/',
  '**/.tistore',

  // target
  '..ccdid',
  '..ccvid',
  '.6226f7cbe59e99a90b5cef6f94f966fd',
  '.7934039a/',
  '.BD_SAPI_CACHE',
  '.COM.TAOBAO.DP',
  '.DATASTORAGE',
  '.DataStorage/',
  '.OAIDSystemConfig/',
  '.Rcs/',
  '.UTSYSTEMCONFIG',
  '.UTSystemConfig/',
  '._android.dat',
  '._driver.dat',
  '.aaa/',
  '.andorid/',
  '.android/',
  '.astable/',
  '.bbb/',
  '.ccc/',
  '.cisgame/',
  '.com.estrongs.android.pop/',
  '.com.kwai.weapon.conjure/',
  '.com.taobao.dp/',
  '.d00/',
  '.duid',
  '.emcoookie',
  '.f_dfpid_com.dianping.v1',
  '.gs_file',
  '.jpush',
  '.oukdtft',
  '.pns',
  '.qmt',
  '.reaper_action_file.txt',
  '.reaper_activate_file.txt',
  '.saf_device/',
  '.tbs/',
  '.tcookieid',
  '.td-3',
  '.tlocalcookieid',
  '.turingdebug/',
  '.vivo/',
  '.xdsd_pin',
  '.xdkj.kr.new.01',
  '.xs-1',
  '.zxcid.dat',
  '1185278458',
  '7ad60021e1db4a24b56fe97b50525ed21',
  'Android/obj/.um',
  'AlivcData/',
  'BaiduNetdisk/',
  'ByteDownload/',
  'Cardboard/',
  'Ccb/',
  'FSaCdeR2e/',
  'Flyertea/',
  'Fonts/',
  'Futu/',
  'HCE_CCB/',
  'ICBC/',
  'ICBCWAPLog/',
  'IndoorMap/',
  'Local/',
  'Log/',
  'Mob/',
  'MSC',
  'OSSLog/',
  'PostLife/',
  'QQBrowser/',
  'Quark/',
  'Sdk/',
  'SysQS/',
  'TMRI_12123/',
  'TbsReaderTemp/',
  'UCDownloads/',
  'UMENG_CACHE',
  'UXTest/',
  'Unicom/',
  'Y2diY2hpbmE/',
  'a/',
  'aegis/',
  'air.tv.douyu.android/',
  'air.tv.douyu.android_KcSdk/',
  'alipay/',
  'app/',
  'autonavi/',
  'b6808aa22d6d4e430ade6201c1dd273a',
  'b919d3c5934a4e27b6a6ce774febfe751',
  'backups/',
  'baidu/',
  'browser/',
  'bytedance/',
  'cainiao/',
  'cmb.pb/',
  'cmb/',
  'cn.futu.trader_KcSdk/',
  'com.MobileTicket/',
  'com.alibaba.android.security.activity/',
  'com.cainiao.wireless/',
  'com.chinaPost.EMSAppandroid/',
  'com.cs_credit_bank/',
  'com.cmcc.cmvid',
  'com.hanweb.android.zhejiang.activity/',
  'com.miui.guardprovider_TMF_TMS/',
  'com.quark.browser/',
  'com.sgcc.wsgw.cn/',
  'com.ifengyu.link/',
  'crash/',
  'data/',
  'douyu/',
  'dsj_log/',
  'duilite/',
  'fcd70f3c7711c0988bd8b9cdccf75794',
  'fps/',
  'guardlibs/',
  'hkhsh/',
  'hot_spot_result/',
  'images/',
  'lesutong/',
  'libs/',
  'miguvideo/',
  'mishop/',
  'monitor/',
  'msc/',
  'netease/',
  'qmt/',
  'qt/',
  'setup/',
  'sessiondll/',
  'sg_data',
  'shoppingstreets/',
  'statistic/',
  'system/',
  'taptap_did/',
  'taptapupdate/',
  'tbs/',
  'tencent/msflogs/',
  'tencent/tbs/',
  'ttscache/',
  'txrtmp/',
  'umeng_cache/',
  'unity_jail/',
  'va_shared/',
  'widgetone/',
  'wsgw_h5/',
  'xhwl/',
  'youku/',

  'Documents/Unicom/',
  'DCIM/.android/',
]

const excludePatterns = [
  'Android/!(obj)/',
]

const matchers = patterns.map(
  pattern => (Array.isArray(pattern) ? mm.matcher(...pattern) : mm.matcher(pattern, { dot: true })),
)

const excludeMatchers = excludePatterns.map(
  pattern => (Array.isArray(pattern) ? mm.matcher(...pattern) : mm.matcher(pattern, { dot: true })),
)

export default (path) => {
  if (excludeMatchers.some(matcher => matcher(path)))
    return -1
  return matchers.some(matcher => matcher(path)) ? 1 : 0
}
